test: &default

  # Credentials for REST APIs
  client_id: AQaCPmJFoefvic4HpULgVFN2wOZCzb0vVjrEp6mISMvNi5TREeq9Ee-oADy5Qpc-wkAxELC4EJjghDXH
  client_secret: EL_MOHCmjjhbjVjuxKjadyehs8X6ALCSbQFV_f-a9sdxyloljIoZKqOyKzT4LWMq3DCPiw-g2n_sEC6J

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: thezmedia-facilitator@hotmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
